skin-schema.json
skin.json

skin.json data validates against skin-schema

[PBW-3307] skin and skin-schema updates

---

skin-schema.json

These updates incorporate more details from the Docs team documentation into the JSON schema "skin-schema.json" describing skin.json.

Merging skin-schema.json

---

en.json
es.json
zh.json

localization for the errors:
OO.ERROR.VC.UNSUPPORTED_ENCODING
OO.ERROR.VC.UNABLE_TO_CREATE_VIDEO_ELEMENT

[PBW-3762] adding localization for errors

---

skin.json

@Matthew-C, @lental please review

[PBW-3590] removing font family and font size for title and description

---

skin.json

This is due to decommissioning stable/latest

[PBW-4095] updated skin.json embed source

---

skin-schema.json
skin.json

adds clickUrl parameter to watermark in control bar.

[PBW-3181] add clickUrl parameter

---

skin.json

NOTE: loading icon will not work until the new image gets to stable branch

[PBW-4508] changing relative to absolute paths

---

skin-schema.json
skin.json

This is related to PR from ios-skin: https://github.com/ooyala/ios-skin/pull/284.

[PBA-2837] Live DVR configuration

---

skin.json

This is in conjunction with pull request below.
https://github.com/ooyala/html5-skin/pull/515
https://github.com/ooyala/skin-config/pull/135
@rchalooyala

[PBW-5174] Update to Icon font opacity. 

---

skin.json

build script will change to stable version

update absolute paths to /candidate/latest/ 

---

skin.json

to accommodate turning thumbnail seeking on/off

[PBW-4144] adding thumbnailPreview setting to skin config

---

skin-schema.json

changed default height from 60 to 90

---

skin.json

found spelling mistake ,changed to default(instead of defualt)

[while working on PBW-5552] 

---

README.md
examples/tv-skin.json
skin-schema.json
skin.json

disable additional properties in the scrubber bar sections

[PBA-4717] add Thumb Color to scrubber bars

---

skin-schema.json
skin.json

https://jira.corp.ooyala.com/browse/PLAYER-22

[PLAYER-22] - Added socialContent property

---

skin-schema.json
skin.json

-added new quality selection config

[player-2011]

---

languageFiles/en.json
languageFiles/es.json
languageFiles/ja.json
languageFiles/zh.json

-removed “Invest in Social Change” translations

[player-2078]

---

examples/tv-skin.json
skin-schema.json
skin.json

There are changes in skin-schema.json , skin.json, tv-skin.json for prevent errors after runing 
```
find . -type f -name "*skin.json" | xargs -I REPL node validate.js skin-schema.json REPL
```

[Bugfix/schema] Changes for validate.js

---

languageFiles/en.json
skin-schema.json
skin.json

Added icons and localized titles for multi audio and CC panels.

[PLAYER-2962] Added changes for multi audio and CC panels

---

languageFiles/en.json
skin-schema.json
skin.json

Reverts ooyala/skin-config#193

Revert "[PLAYER-2962] Added changes for multi audio and CC panels"

---

languageFiles/en.json
languageFiles/es.json
languageFiles/ja.json
languageFiles/ko.json
languageFiles/zh.json

Commas in the end of all language files were removed.

[config/no-commas] remove commas in language files

---

skin.json

I forgot that I had discussed this with Steve, and he had mentioned that skip buttons would be opt-in, so I'm disabling them by default.

[PLAYER-3475] Disabling skip buttons by default

---

languageFiles/en.json
skin-schema.json
skin.json

This is just the basic configuration with the default options. More settings might be needed in the future.
Added two new strings for the English language file which will need to be translated.

[PLAYER-3645] Added base configuration for playback speed controls

---

languageFiles/es.json
languageFiles/ja.json
languageFiles/ko.json
languageFiles/zh.json

Update some spanish and chinese translations. Also add missing ones but still not translated

[PLAYER-3837] Update translations

---

languageFiles/ja.json
languageFiles/zh.json

English and Spanish already existed. Korean is pending

[PLAYER-4082] Added playback speed translations for Japanese and Chinese

---

skin.json

-setting false as default for audio only

[audio-only-default]

---

skin-schema.json
skin.json

- added button for playbackSpeed feature (for mobile content)
Ticket: https://jira.corp.ooyala.com/browse/PLAYER-4007

[PLAYER-4007] Added playbackSpeed button for mobile content

---

languageFiles/en.json
languageFiles/es.json
languageFiles/ja.json
languageFiles/ko.json
languageFiles/zh.json

fix/PLAYER-4755 CastPanel translation added

---

languageFiles/zh.json

fix/PLAYER-4755 Chinese locale updated

---

skin-schema.json
skin.json

- added separated buttons for Web and SDK into audio only category
- updated `skin-schema.json` to support new buttons

[PLAYER-4641] Added separated buttons for Web and SDK into audio only category

---

skin.json

Add AirPlay button to Web Player UI
https://jira.corp.ooyala.com/browse/PLAYER-4114

[feature/PLAYER-4114] Adding the AirPlay button

---

skin.json

https://jira.corp.ooyala.com/browse/PLAYER-5094

AirPlay added the icon for 'active' state

---

languageFiles/en.json
languageFiles/es.json
languageFiles/ja.json
languageFiles/ko.json
languageFiles/zh.json

Keys  for accessibility of navigation buttons (for video 360)  were added.
There are no translations available in languages other than English.
[Related PR](https://github.com/ooyala/html5-skin/pull/1242)

bugfix/PLAYER-5121 Improve 360 video accessibility

---

skin-schema.json
skin.json

Add settings for cast panel: possibility to enable/disable cast button, skip and switch buttons. 
Add settings to manage time for skipping. 
Add settings to manage color of items in Devices screen. 
Add schema with description for all of above.

[PLAYER-5035] Add setting for skin in cast mode and schema for it.

---

Jenkinsfile

[PLAYER-5247] Establish CI for skin-config
